### ISSUE TITLE
Html 뷰 생성

### ISSUE THREAD

**Issue by Domae-back-end** [cocktail-board/kacktaeil#9]
HTML 템플릿을 검색하여 칵테일 프로젝트에 맞게 수정 작업한다.

**Comment by Domae-back-end** [comment]
user index.html 생성
admin index.html 생성

**Comment by munyeol-Yoon** [comment]
admin mypage.html 생성

**Comment by munyeol-Yoon** [comment]
user/ ----
             + main_page/ ----
                                         + board_create.html
                                         + board_update.html
                                         + index.html
                                         + mypage.html
             + index.html
